using System.ComponentModel.DataAnnotations;

namespace SchoolMvc.Models;

/// <summary>
/// Represents a subject that students can register for. This model maps to the Subject table.
/// </summary>
public class Subject
{
    /// <summary>
    /// Primary key generated by the database.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Name of the subject (for example, "Mathematics").
    /// </summary>
    [Required]
    [StringLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Number of teaching slots allocated to the subject.
    /// </summary>
    [Range(1, int.MaxValue, ErrorMessage = "Number of slots must be greater than zero.")]
    public int NumberOfSlot { get; set; }

    /// <summary>
    /// Navigation property for the courses that belong to this subject.
    /// </summary>
    public ICollection<Course> Courses { get; set; } = new List<Course>();
}
